version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/mock-battery"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/mock-pv"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/mock-dbus"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
