sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5
sonar.issue.ignore.multicriteria.e1.ruleKey=docker:S8431
sonar.issue.ignore.multicriteria.e1.resourceKey=**/Dockerfile*
sonar.issue.ignore.multicriteria.e2.ruleKey=docker:S8541
sonar.issue.ignore.multicriteria.e2.resourceKey=**/Dockerfile*
sonar.issue.ignore.multicriteria.e3.ruleKey=shelldre:S7688
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.sh
sonar.issue.ignore.multicriteria.e4.ruleKey=shelldre:S7677
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.sh
sonar.issue.ignore.multicriteria.e5.ruleKey=shelldre:S100
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.sh
